//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "candidate_interview_answers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub candidate_interview_id: i32,
    pub interview_template_question_id: i32,
    pub score: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub comments: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::candidate_interviews::Entity",
        from = "Column::CandidateInterviewId",
        to = "super::candidate_interviews::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CandidateInterviews,
    #[sea_orm(
        belongs_to = "super::interview_template_questions::Entity",
        from = "Column::InterviewTemplateQuestionId",
        to = "super::interview_template_questions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    InterviewTemplateQuestions,
}

impl Related<super::candidate_interviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateInterviews.def()
    }
}

impl Related<super::interview_template_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewTemplateQuestions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
