//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "candidate_interviews")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub candidate_process_id: i32,
    pub interview_template_id: i32,
    pub interviewer_id: i32,
    pub status: i32,
    pub scheduled_at: Option<DateTime>,
    pub started_at: DateTime,
    pub finished_at: Option<DateTime>,
    pub interview_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub overall_comments: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub final_score: Option<Decimal>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::candidate_interview_answers::Entity")]
    CandidateInterviewAnswers,
    #[sea_orm(
        belongs_to = "super::candidate_processes::Entity",
        from = "Column::CandidateProcessId",
        to = "super::candidate_processes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CandidateProcesses,
    #[sea_orm(
        belongs_to = "super::interview_status::Entity",
        from = "Column::Status",
        to = "super::interview_status::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    InterviewStatus,
    #[sea_orm(
        belongs_to = "super::interview_templates::Entity",
        from = "Column::InterviewTemplateId",
        to = "super::interview_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    InterviewTemplates,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::InterviewerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::candidate_interview_answers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateInterviewAnswers.def()
    }
}

impl Related<super::candidate_processes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateProcesses.def()
    }
}

impl Related<super::interview_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewStatus.def()
    }
}

impl Related<super::interview_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewTemplates.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
