//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "candidate_applications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub candidate_id: i32,
    pub position_id: i32,
    pub status: String,
    pub started_at: DateTime,
    pub finished_at: Option<DateTime>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub final_score: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub final_comments: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::candidates::Entity",
        from = "Column::CandidateId",
        to = "super::candidates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Candidates,
    #[sea_orm(has_many = "super::interviews::Entity")]
    Interviews,
    #[sea_orm(
        belongs_to = "super::positions::Entity",
        from = "Column::PositionId",
        to = "super::positions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Positions,
}

impl Related<super::candidates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Candidates.def()
    }
}

impl Related<super::interviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Interviews.def()
    }
}

impl Related<super::positions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Positions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
