//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interview_questions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub interview_id: i32,
    pub question_id: i32,
    pub question_order: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub score: Option<Decimal>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::interviews::Entity",
        from = "Column::InterviewId",
        to = "super::interviews::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Interviews,
    #[sea_orm(
        belongs_to = "super::questions::Entity",
        from = "Column::QuestionId",
        to = "super::questions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Questions,
}

impl Related<super::interviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Interviews.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Questions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
