//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interview_templates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub position_id: i32,
    pub name: String,
    pub status: i32,
    pub created_by: i32,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::candidate_interviews::Entity")]
    CandidateInterviews,
    #[sea_orm(
        belongs_to = "super::interview_status::Entity",
        from = "Column::Status",
        to = "super::interview_status::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    InterviewStatus,
    #[sea_orm(has_many = "super::interview_template_questions::Entity")]
    InterviewTemplateQuestions,
    #[sea_orm(
        belongs_to = "super::positions::Entity",
        from = "Column::PositionId",
        to = "super::positions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Positions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::candidate_interviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateInterviews.def()
    }
}

impl Related<super::interview_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewStatus.def()
    }
}

impl Related<super::interview_template_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewTemplateQuestions.def()
    }
}

impl Related<super::positions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Positions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
