//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interview_status")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::candidate_interviews::Entity")]
    CandidateInterviews,
    #[sea_orm(has_many = "super::interview_templates::Entity")]
    InterviewTemplates,
}

impl Related<super::candidate_interviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateInterviews.def()
    }
}

impl Related<super::interview_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewTemplates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
