//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interviews")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub candidate_application_id: i32,
    pub interviewer_id: i32,
    pub name: String,
    pub interview_type: String,
    pub status: String,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub score: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub comments: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::candidate_applications::Entity",
        from = "Column::CandidateApplicationId",
        to = "super::candidate_applications::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CandidateApplications,
    #[sea_orm(has_many = "super::interview_questions::Entity")]
    InterviewQuestions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::InterviewerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::candidate_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateApplications.def()
    }
}

impl Related<super::interview_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewQuestions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
