//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interview_template_questions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub interview_template_id: i32,
    pub question_id: i32,
    pub question_order: i32,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::candidate_interview_answers::Entity")]
    CandidateInterviewAnswers,
    #[sea_orm(
        belongs_to = "super::interview_templates::Entity",
        from = "Column::InterviewTemplateId",
        to = "super::interview_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    InterviewTemplates,
    #[sea_orm(
        belongs_to = "super::questions::Entity",
        from = "Column::QuestionId",
        to = "super::questions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Questions,
}

impl Related<super::candidate_interview_answers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateInterviewAnswers.def()
    }
}

impl Related<super::interview_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewTemplates.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Questions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
