//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "locations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub city: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::position_locations::Entity")]
    PositionLocations,
}

impl Related<super::position_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionLocations.def()
    }
}

impl Related<super::positions::Entity> for Entity {
    fn to() -> RelationDef {
        super::position_locations::Relation::Positions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::position_locations::Relation::Locations.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
