//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "positions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_by: i32,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status: String,
    pub work_model: String,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::candidate_applications::Entity")]
    CandidateApplications,
    #[sea_orm(has_many = "super::position_locations::Entity")]
    PositionLocations,
    #[sea_orm(has_many = "super::position_stacks::Entity")]
    PositionStacks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::candidate_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateApplications.def()
    }
}

impl Related<super::position_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionLocations.def()
    }
}

impl Related<super::position_stacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionStacks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::locations::Entity> for Entity {
    fn to() -> RelationDef {
        super::position_locations::Relation::Locations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::position_locations::Relation::Positions.def().rev())
    }
}

impl Related<super::stacks::Entity> for Entity {
    fn to() -> RelationDef {
        super::position_stacks::Relation::Stacks.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::position_stacks::Relation::Positions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
