//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "positions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status: i32,
    pub created_by: i32,
    pub created_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::candidate_processes::Entity")]
    CandidateProcesses,
    #[sea_orm(has_many = "super::interview_templates::Entity")]
    InterviewTemplates,
    #[sea_orm(has_many = "super::position_stacks::Entity")]
    PositionStacks,
    #[sea_orm(
        belongs_to = "super::position_status::Entity",
        from = "Column::Status",
        to = "super::position_status::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PositionStatus,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::candidate_processes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateProcesses.def()
    }
}

impl Related<super::interview_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewTemplates.def()
    }
}

impl Related<super::position_stacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionStacks.def()
    }
}

impl Related<super::position_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionStatus.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::stacks::Entity> for Entity {
    fn to() -> RelationDef {
        super::position_stacks::Relation::Stacks.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::position_stacks::Relation::Positions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
