//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

#![allow(unused_imports)]
pub use super::candidate_applications::Entity as CandidateApplications;
pub use super::candidates::Entity as Candidates;
pub use super::interview_questions::Entity as InterviewQuestions;
pub use super::interview_reviewers::Entity as InterviewReviewers;
pub use super::interviews::Entity as Interviews;
pub use super::position_stacks::Entity as PositionStacks;
pub use super::positions::Entity as Positions;
pub use super::questions::Entity as Questions;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::stacks::Entity as Stacks;
pub use super::users::Entity as Users;
