//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "process_status")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::candidate_processes::Entity")]
    CandidateProcesses,
}

impl Related<super::candidate_processes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandidateProcesses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
