//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "questions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub stack_id: i32,
    #[sea_orm(column_type = "Text")]
    pub question: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub acceptable_answer: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::interview_questions::Entity")]
    InterviewQuestions,
    #[sea_orm(
        belongs_to = "super::stacks::Entity",
        from = "Column::StackId",
        to = "super::stacks::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stacks,
}

impl Related<super::interview_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterviewQuestions.def()
    }
}

impl Related<super::stacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stacks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
