//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stacks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::position_stacks::Entity")]
    PositionStacks,
    #[sea_orm(has_many = "super::questions::Entity")]
    Questions,
}

impl Related<super::position_stacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionStacks.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Questions.def()
    }
}

impl Related<super::positions::Entity> for Entity {
    fn to() -> RelationDef {
        super::position_stacks::Relation::Positions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::position_stacks::Relation::Stacks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
